[book]
authors = ["Jens Chr. Larsen"]
language = "da"
multilingual = false
src = "src"
title = "Den lille bog om design af fysiske prototyper"

[output.html]
git-repository-url = "https://github.com/jechla/den-lille-bog-om-design-af-fysiske-prototyper"